[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[projct]
name = "gymnasium_env_jae"
version = "0.0.1"
dependencies = [
    "gymnasium",
    "pygame",
    "pre-commit",
]